### ISSUE TITLE
Summary.razor line 412: "System.ArgumentException:  is not a valid manager status"

### ISSUE THREAD

**Issue by andreasalstrup** [P3SW/P3#93]
Crash log:

Starting new manager
New manager name is dk.aes.ans.konvertering.managers.progress.progressRevision.ProgressRevisionManager
Manager dk.aes.ans.konvertering.managers.progress.progressRevision.ProgressRevisionManager started
Manager dk.aes.ans.konvertering.managers.progress.progressRevision.ProgressRevisionManager started with execution_id 4
MANAGER START TIME IS: 10/28/2021 4:15:50 PM

**Comment by Bisgaard01** [comment]
Fixed with pull request #92
